mybatis-plus:
  datasource:
    url: jdbc:mysql://test.bjpygh.com/pygh
    username: root
    password: P@gh202o
  global-config:
    author: wengjk
    swagger: true
    output-dir: /Users/piaoyangguohai/IdeaProjects/mybatisModelGen/src/main/java/
  package-config:
    parent: com.bjpygh
    module-name: demandApply
    mapper-xml-dir: /Users/piaoyangguohai/IdeaProjects/mybatisModelGen/src/main/resources/mapper
  strategy-config:
    include-tables:
      - da_offline_invitation
      - da_offline_official_people
