mybatis-plus:
  datasource:
    url: jdbc:mysql://test.bjpygh.com/example_db
    username: root
    password: P@gh202o
  global-config:
    author: wengjk
    swagger: true
    output-dir: /Users/wengjk/project/IdeaProjects/mybatisModelGen/src/main/java/
  package-config:
    parent: com.bjpygh
    module-name: example_module_name
    mapper-xml-dir: /Users/wengjk/project/IdeaProjects/mybatisModelGen/src/main/resources/mapper
  strategy-config:
    include-tables:
      - example_table_name1
      - example_table_name2
